### ISSUE TITLE
Allow mirroring / propagating messages from discord channel

### ISSUE THREAD

**Issue by BurnySc2** [aiarena/aiarena-discordbot#21]
The purpose is to have one main channel where a discussion is happening and have it being redirected to channels from other discord channels.

This feature needs to have an input channel (server + channel) and a list of output channels (server + channel). Alternatively discord webhooks can also be used for output channels.

Would the list of channels be hardcoded?
The problem might be when messages are being edited or updated - how would that be handled?

**Comment by lladdy** [comment]
@BurnySc2 was this related to having multiple discords?
Asking in case this can be closed now.

**Comment by BurnySc2** [comment]
Indeed, the idea was to have one source-/input-discord and one or more output-discord servers to synchronize chat channels, so people wouldn't have to join multiple discord servers.

Discord already has this feature, but only for announcement-channels which you can `follow` and so the announcements get also posted in other discords. Very useful for something like patches or updates.

**Comment by lladdy** [comment]
Okay great - sounds like we can close this now then, seeing as it's just the one Discord.
Feel free to re-open if you think there's still a reason to implement this.
